### ISSUE TITLE
Dynamic desktop resizing does not work

### ISSUE THREAD

**Issue by xerces8** [EtienneBarbier/Hyper-V-RedHat-VM#10]
I have Windows 11 and installer Oracle Linux 8.10
Using your script I enabled xrdp (without the audio part).

It works, except Dynamic Desktop Resizing

That is, I can not resize the VM window.

I have the same problem with Ubuntu 22.04 LTS guest VM (set up via Quick Create, it uses a customized Ubuntu image, preconfigured for Hyper-V): it has working RDP out of the box, but without dynamic resizing.

A VM with Windows 10 has this working.

Any idea what is going on?

**Comment by xerces8** [comment]
Some research on the web hints that this never worked. As is: this is by design

**Comment by EtienneBarbier** [comment]
Hello, yep, that's not working, need to close an init the new window with the desired size.
