### ISSUE TITLE
Do you have an update for RHEL9 VMs?

### ISSUE THREAD

**Issue by dcfsc** [EtienneBarbier/Hyper-V-RedHat-VM#3]
I have tried using this on RHEL9.4 VMs in Hyper-V on an Azure Virtual Desktop for work and the clipboard does not work. A GUI VM without a clipboard to the host is basically useless.
FYI the graphics performance is pretty bad too. The mouse is very sloppy and laggy. An Ubuntu 22.04 VM installed using Quick Create is snappy and perfect. Sigh.

**Comment by EtienneBarbier** [comment]
Hello, i will try to make it work for RHEL 9 this week.

**Comment by dcfsc** [comment]
> Hello, i will try to make it work for RHEL 9 this week.

I would be happy to try anything out. Some guidance on uninstalling the RHEL8 packages if necessary would be helpful.

**Comment by EtienneBarbier** [comment]
Hello, i created a PR with RHEL9 support. It works on my side.
If you wish to test on your side, i'll wait until your approval ;)

**Comment by dcfsc** [comment]
Going thru the install:
```
PS C:\Windows\system32> net localgroup "Hyper-V Administrators" "myid"
The syntax of this command is:

NET LOCALGROUP
[groupname [/COMMENT:"text"]] [/DOMAIN]
              groupname {/ADD [/COMMENT:"text"] | /DELETE}  [/DOMAIN]
              groupname name [...] {/ADD | /DELETE} [/DOMAIN]

are we missing the /ADD option?
```

There are items like 
`This script is only for Rhel 8 or Centos 8 OS.`
Is that the case still? Is RHEL9 supported? Apologies if the README is still under development.

**Comment by dcfsc** [comment]
Looks like the `net localgroup` was fixed in another branch. Great!

The clipboard in RHEL9 is still not accepting items from the host AVD. I did notice that the `xrdp` daemon is running on port 3390 instead of 3389 (since the Remote Desktop session from my home box to the Azure Virtual Desktop is also using the 3389 port, and ports are shared due to the networking). 

If the port is different, would something else need to be configured?

/etc/xrdp/xrdp.ini

    port=vsock://-1:3390

Also, pasting from the Hyper-V "Type Clipboard Text" results in text like:

`=ddddc`  or `=m,bb=+d=ddb/vb/vmbm.xd`

IS there a log anywhere I can try to debug events such as clipboard?

I realize the AVD environment is pretty different from a hardware host running HyperV, with nested virtualization and all. So this may never work.

**Comment by EtienneBarbier** [comment]
For the /ADD you got the answer :)
For `This script is only for Rhel 8 or Centos 8 OS.`, i need to change it.

**Comment by EtienneBarbier** [comment]
Are you able to size the VM window as you wish ?

**Comment by dcfsc** [comment]
> Are you able to size the VM window as you wish ?

Using the Displays applet of RHEL9 Settings I am able to change the screen resolution nicely. 

Interestingly, it prompts to revert the settings for 15 seconds. If I accept revert, it logs me out.

**Comment by EtienneBarbier** [comment]
Hum, do you have this prompt when you are connecting to the VM 
![image](https://github.com/user-attachments/assets/e059dee8-5b2e-4fa6-8cda-97d4cdae00c7)
?

**Comment by EtienneBarbier** [comment]
I have no idea if it works with another port configured for xrdp. I did'nt found anything about this topic. It may require a modification on Hyper-V side, but i don't know which.

**Comment by dcfsc** [comment]
I did notice that. It looks like the box for Remote Desktop. I am using the UI for HyperV, not remote desktop. My interface looks like: 
![image](https://github.com/user-attachments/assets/5cfad038-978f-4a2b-9909-19c91ed3cc8e)

Actually, I cannot connect to the VM using RDP from the host. Tried ip:3390 and error.

**Comment by EtienneBarbier** [comment]
Okay so Enhanced Session Mode is not activated in your screenshot.
If ESM is activated, you should have this icon not grayed 
![image](https://github.com/user-attachments/assets/bdd3b684-0fc3-408f-ae35-f2ab2df9f2d9)

I tried locally to change the port of xrdp (with new port open in firewall) and it did'nt work. Looks like Hyper-V scan only port 3389 to initiate RDP.

**Comment by dcfsc** [comment]
> Okay so Enhanced Session Mode is not activated in your screenshot. If ESM is activated, you should have this icon not grayed 

Maybe because it cannot talk to the VM.

> I tried locally to change the port of xrdp (with new port open in firewall) and it did'nt work. Looks like Hyper-V scan only port 3389 to initiate RDP.

With an Azure Virtual Desktop the port is locked down to 3389, so I guess this is done. Strange that an Ubuntu 22 VM works perfectly when you choose it from a "quick create". I wish RedHat would make the experience as nice.  Thanks for your effort.
